simFun97 = function() {
  #we want to generate ~n points
  nPerUnit = ppp97$n/Area
  
  #use lognormal distribution to estimate mean number of points generated by rLGCP
  #based on this algebra:
  #exp(mu + var/2) = n
  #mu = log(n) - var/2
  #increase this mu estimate by 3 times to make sure we generate too many points
  varEst = betaMLE^2*varianceMLE
  overallMuEst = log(nPerUnit) - varEst/2
  # overGenMu = overallMuEst*log(3) # don't overgenerate points because we shouldn't randomly thin
  
  #
  sim = rLGCP("exp", overallMuEst, var=betaMLE^2*varianceMLE, scale=scaleMLE, 
              nsim=1, win=win, drop=TRUE)
  
  #dont do random thinning, we must have a random number of points
#   #random thinning until we get to n points
#   samp = sample(1:sim$n, n)
#   sim$n=n
#   sim$x = sim$x[samp]
#   sim$y = sim$y[samp]
#   sim$marks = sim$marks[samp]
  
  return(sim)
}

K = function(s, beta=betaMLE, sill=sillMLE, scale=scaleMLE) {
  gammaU = function(u) {
    # u*(exp(beta*sill*Matern(u, range=scale) - 1))
    u*(exp(beta^2*sill*Matern(u, range=scale)) - 1)
  }
  
  pi*s^2 + 2*pi*integrate(gammaU, 0, s)$value
}